// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class MapController
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mapControllerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.MapController";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CurrentZoomLevel("CurrentZoomLevel"),
		ZoomToLat("ZoomToLat"),
		ZoomToLon("ZoomToLon"),
		ZoomToGlobalId("ZoomToGlobalId"),
		MouseLat("MouseLat"),
		MouseLon("MouseLon"),
		GlobalID("GlobalID"),
		AssetAsJSON("AssetAsJSON"),
		Switch_ZoomToLatLon("Switch_ZoomToLatLon"),
		Switch_ZoomToGlobalID("Switch_ZoomToGlobalID"),
		bookmarksJSON("bookmarksJSON");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MapController(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.MapController"));
	}

	protected MapController(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mapControllerMendixObject)
	{
		if (mapControllerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.MapController", mapControllerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.MapController");

		this.mapControllerMendixObject = mapControllerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MapController.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.MapController initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.MapController.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.MapController initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.MapController(context, mendixObject);
	}

	public static myfirstmodule.proxies.MapController load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.MapController.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CurrentZoomLevel
	 */
	public final java.math.BigDecimal getCurrentZoomLevel()
	{
		return getCurrentZoomLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentZoomLevel
	 */
	public final java.math.BigDecimal getCurrentZoomLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.CurrentZoomLevel.toString());
	}

	/**
	 * Set value of CurrentZoomLevel
	 * @param currentzoomlevel
	 */
	public final void setCurrentZoomLevel(java.math.BigDecimal currentzoomlevel)
	{
		setCurrentZoomLevel(getContext(), currentzoomlevel);
	}

	/**
	 * Set value of CurrentZoomLevel
	 * @param context
	 * @param currentzoomlevel
	 */
	public final void setCurrentZoomLevel(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal currentzoomlevel)
	{
		getMendixObject().setValue(context, MemberNames.CurrentZoomLevel.toString(), currentzoomlevel);
	}

	/**
	 * @return value of ZoomToLat
	 */
	public final java.lang.String getZoomToLat()
	{
		return getZoomToLat(getContext());
	}

	/**
	 * @param context
	 * @return value of ZoomToLat
	 */
	public final java.lang.String getZoomToLat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ZoomToLat.toString());
	}

	/**
	 * Set value of ZoomToLat
	 * @param zoomtolat
	 */
	public final void setZoomToLat(java.lang.String zoomtolat)
	{
		setZoomToLat(getContext(), zoomtolat);
	}

	/**
	 * Set value of ZoomToLat
	 * @param context
	 * @param zoomtolat
	 */
	public final void setZoomToLat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zoomtolat)
	{
		getMendixObject().setValue(context, MemberNames.ZoomToLat.toString(), zoomtolat);
	}

	/**
	 * @return value of ZoomToLon
	 */
	public final java.lang.String getZoomToLon()
	{
		return getZoomToLon(getContext());
	}

	/**
	 * @param context
	 * @return value of ZoomToLon
	 */
	public final java.lang.String getZoomToLon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ZoomToLon.toString());
	}

	/**
	 * Set value of ZoomToLon
	 * @param zoomtolon
	 */
	public final void setZoomToLon(java.lang.String zoomtolon)
	{
		setZoomToLon(getContext(), zoomtolon);
	}

	/**
	 * Set value of ZoomToLon
	 * @param context
	 * @param zoomtolon
	 */
	public final void setZoomToLon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zoomtolon)
	{
		getMendixObject().setValue(context, MemberNames.ZoomToLon.toString(), zoomtolon);
	}

	/**
	 * @return value of ZoomToGlobalId
	 */
	public final java.lang.String getZoomToGlobalId()
	{
		return getZoomToGlobalId(getContext());
	}

	/**
	 * @param context
	 * @return value of ZoomToGlobalId
	 */
	public final java.lang.String getZoomToGlobalId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ZoomToGlobalId.toString());
	}

	/**
	 * Set value of ZoomToGlobalId
	 * @param zoomtoglobalid
	 */
	public final void setZoomToGlobalId(java.lang.String zoomtoglobalid)
	{
		setZoomToGlobalId(getContext(), zoomtoglobalid);
	}

	/**
	 * Set value of ZoomToGlobalId
	 * @param context
	 * @param zoomtoglobalid
	 */
	public final void setZoomToGlobalId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zoomtoglobalid)
	{
		getMendixObject().setValue(context, MemberNames.ZoomToGlobalId.toString(), zoomtoglobalid);
	}

	/**
	 * @return value of MouseLat
	 */
	public final java.lang.String getMouseLat()
	{
		return getMouseLat(getContext());
	}

	/**
	 * @param context
	 * @return value of MouseLat
	 */
	public final java.lang.String getMouseLat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MouseLat.toString());
	}

	/**
	 * Set value of MouseLat
	 * @param mouselat
	 */
	public final void setMouseLat(java.lang.String mouselat)
	{
		setMouseLat(getContext(), mouselat);
	}

	/**
	 * Set value of MouseLat
	 * @param context
	 * @param mouselat
	 */
	public final void setMouseLat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mouselat)
	{
		getMendixObject().setValue(context, MemberNames.MouseLat.toString(), mouselat);
	}

	/**
	 * @return value of MouseLon
	 */
	public final java.lang.String getMouseLon()
	{
		return getMouseLon(getContext());
	}

	/**
	 * @param context
	 * @return value of MouseLon
	 */
	public final java.lang.String getMouseLon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MouseLon.toString());
	}

	/**
	 * Set value of MouseLon
	 * @param mouselon
	 */
	public final void setMouseLon(java.lang.String mouselon)
	{
		setMouseLon(getContext(), mouselon);
	}

	/**
	 * Set value of MouseLon
	 * @param context
	 * @param mouselon
	 */
	public final void setMouseLon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mouselon)
	{
		getMendixObject().setValue(context, MemberNames.MouseLon.toString(), mouselon);
	}

	/**
	 * @return value of GlobalID
	 */
	public final java.lang.String getGlobalID()
	{
		return getGlobalID(getContext());
	}

	/**
	 * @param context
	 * @return value of GlobalID
	 */
	public final java.lang.String getGlobalID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GlobalID.toString());
	}

	/**
	 * Set value of GlobalID
	 * @param globalid
	 */
	public final void setGlobalID(java.lang.String globalid)
	{
		setGlobalID(getContext(), globalid);
	}

	/**
	 * Set value of GlobalID
	 * @param context
	 * @param globalid
	 */
	public final void setGlobalID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String globalid)
	{
		getMendixObject().setValue(context, MemberNames.GlobalID.toString(), globalid);
	}

	/**
	 * @return value of AssetAsJSON
	 */
	public final java.lang.String getAssetAsJSON()
	{
		return getAssetAsJSON(getContext());
	}

	/**
	 * @param context
	 * @return value of AssetAsJSON
	 */
	public final java.lang.String getAssetAsJSON(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssetAsJSON.toString());
	}

	/**
	 * Set value of AssetAsJSON
	 * @param assetasjson
	 */
	public final void setAssetAsJSON(java.lang.String assetasjson)
	{
		setAssetAsJSON(getContext(), assetasjson);
	}

	/**
	 * Set value of AssetAsJSON
	 * @param context
	 * @param assetasjson
	 */
	public final void setAssetAsJSON(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assetasjson)
	{
		getMendixObject().setValue(context, MemberNames.AssetAsJSON.toString(), assetasjson);
	}

	/**
	 * @return value of Switch_ZoomToLatLon
	 */
	public final java.lang.Boolean getSwitch_ZoomToLatLon()
	{
		return getSwitch_ZoomToLatLon(getContext());
	}

	/**
	 * @param context
	 * @return value of Switch_ZoomToLatLon
	 */
	public final java.lang.Boolean getSwitch_ZoomToLatLon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Switch_ZoomToLatLon.toString());
	}

	/**
	 * Set value of Switch_ZoomToLatLon
	 * @param switch_zoomtolatlon
	 */
	public final void setSwitch_ZoomToLatLon(java.lang.Boolean switch_zoomtolatlon)
	{
		setSwitch_ZoomToLatLon(getContext(), switch_zoomtolatlon);
	}

	/**
	 * Set value of Switch_ZoomToLatLon
	 * @param context
	 * @param switch_zoomtolatlon
	 */
	public final void setSwitch_ZoomToLatLon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean switch_zoomtolatlon)
	{
		getMendixObject().setValue(context, MemberNames.Switch_ZoomToLatLon.toString(), switch_zoomtolatlon);
	}

	/**
	 * @return value of Switch_ZoomToGlobalID
	 */
	public final java.lang.Boolean getSwitch_ZoomToGlobalID()
	{
		return getSwitch_ZoomToGlobalID(getContext());
	}

	/**
	 * @param context
	 * @return value of Switch_ZoomToGlobalID
	 */
	public final java.lang.Boolean getSwitch_ZoomToGlobalID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Switch_ZoomToGlobalID.toString());
	}

	/**
	 * Set value of Switch_ZoomToGlobalID
	 * @param switch_zoomtoglobalid
	 */
	public final void setSwitch_ZoomToGlobalID(java.lang.Boolean switch_zoomtoglobalid)
	{
		setSwitch_ZoomToGlobalID(getContext(), switch_zoomtoglobalid);
	}

	/**
	 * Set value of Switch_ZoomToGlobalID
	 * @param context
	 * @param switch_zoomtoglobalid
	 */
	public final void setSwitch_ZoomToGlobalID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean switch_zoomtoglobalid)
	{
		getMendixObject().setValue(context, MemberNames.Switch_ZoomToGlobalID.toString(), switch_zoomtoglobalid);
	}

	/**
	 * @return value of bookmarksJSON
	 */
	public final java.lang.String getbookmarksJSON()
	{
		return getbookmarksJSON(getContext());
	}

	/**
	 * @param context
	 * @return value of bookmarksJSON
	 */
	public final java.lang.String getbookmarksJSON(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.bookmarksJSON.toString());
	}

	/**
	 * Set value of bookmarksJSON
	 * @param bookmarksjson
	 */
	public final void setbookmarksJSON(java.lang.String bookmarksjson)
	{
		setbookmarksJSON(getContext(), bookmarksjson);
	}

	/**
	 * Set value of bookmarksJSON
	 * @param context
	 * @param bookmarksjson
	 */
	public final void setbookmarksJSON(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bookmarksjson)
	{
		getMendixObject().setValue(context, MemberNames.bookmarksJSON.toString(), bookmarksjson);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mapControllerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.MapController that = (myfirstmodule.proxies.MapController) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.MapController";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
